Areas/Admin/Controllers/SliderController.cs
using g139010027_Proje.Areas.Admin.Models;
using g139010027_Proje.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace g139010027_Proje.Areas.Admin.Controllers
{
    public class SliderController : Controller
    {
        OtickDbEntities db = new OtickDbEntities();

        // GET: Admin/Slider
        public ActionResult Index()
        {
           var model= db.Yazilar.OrderByDescending(x=>x.YaziID).ToList();
            return View(model);
        }
        public ActionResult Add() {
            
            return View();

        }
        public ActionResult Delete(int id)
        {
            var model=db.Yazilar.Find(id);
            return View(model);

        }
        public ActionResult DeleteConfirm(int id)
        {
            var model = db.Yazilar.Find(id);
            db.Yazilar.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model=db.Yazilar.Find(id);
            return View(model);

        }
        [HttpPost]
        public ActionResult Edit(SliderModel model)
        {
            if (ModelState.IsValid)
            {



                var bulunan = db.Yazilar.Find(model.YaziID);
                bulunan.YaziBaslik = model.YaziBaslik;
                bulunan.YaziIcerik = model.YaziIcerik;
                bulunan.YaziTarih = model.YaziTarih;
          

                db.SaveChanges();
            }
            //else
            //{
            //    return View(model);
            //}
            return RedirectToAction("Index");

        }
        const string imageFolderPath = "/Content/img/";
        public ActionResult AddSlider(SliderModel model) {
            if (ModelState.IsValid)
            {
                string fileName = string.Empty;
                //dosya kaydetme
                if (model.YaziResim!=null&&model.YaziResim.ContentLength>0)
                {
                     fileName = model.YaziResim.FileName;
                    var path= Path.Combine(Server.MapPath("~" + imageFolderPath),fileName);

                     model.YaziResim.SaveAs(path);
                }
                //ef nesnesi
                Yazilar hb = new Yazilar();
                hb.YaziIcerik = model.YaziIcerik;
                hb.YaziBaslik = model.YaziBaslik;
                hb.YaziTarih = model.YaziTarih;
             
                hb.YaziResim =imageFolderPath + fileName;

                db.Yazilar.Add(hb);
               db.SaveChanges();
            }
            return RedirectToAction("Index");

        }

    }
}

Areas/Admin/Views/Slider/Add.cshtml
@model g139010027_Proje.Areas.Admin.Models.SliderModel

@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>
    Slider Ekleme
</h1>
@using (Html.BeginForm("AddSlider", "Slider", FormMethod.Post, new { @class = "form-horizontal",enctype="multipart/form-data" }))
{
     
   
        <!-- general form elements disabled -->
        <div class="box box-warning">
            <div class="box-header with-border">
                <h3 class="box-title">Yeni Slider Ekleme</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <form role="form">
                    <div class="form-group">
                        <label class="col-sm-3 control-label">@Html.LabelFor(m => m.YaziBaslik)</label>
                        <div class="col-sm-6">
                            @Html.TextBoxFor(m => m.YaziBaslik, new { @class = "form-control", placeholder = "Yazı Başlık" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">@Html.LabelFor(m => m.YaziIcerik) </label>
                        <div class="col-sm-6">
                            @Html.TextAreaFor(m => m.YaziIcerik, new { @class = "form-control", placeholder = "Yazı Detay" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">@Html.LabelFor(m => m.YaziTarih)</label>
                    <div class="col-sm-6">
                         <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                                    </div>
        @Html.TextBoxFor(m => m.YaziTarih, new { @class = "form-control datepicker", placeholder = "Gün/Ay/Yıl", id = "datemask" })
    </div>

</div><!-- /.input group -->
                    </div><!-- /.form group -->
                        

            
                    <div class="form-group">
                        <label class="col-sm-3 control-label">@Html.LabelFor(m => m.YaziResim)</label>
                        <div class="col-sm-6">
                            @Html.TextBoxFor(m => m.YaziResim, new { @class = "form-control", placeholder = "Yazi Resim", type = "file" })
                        </div>
                    </div>


                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-sm-6 col-sm-offset-3">
                                <div class="btn-toolbar">
                                    <button type="submit" class="btn btn-default">İPTAL</button>
                                    <button type="submit" class="btn btn-primary pull-right">EKLE</button>
                                </div>
                            </div>
                        </div>

                    </div>
                </form>    
            </div>  
         
            </div>
       
        }
    @section plugincss{
        <link rel="stylesheet" href="~/Areas/Content/plugins/timepicker/bootstrap-timepicker.css">
<link rel="stylesheet" href="~/Areas/Content/plugins/timepicker/bootstrap-timepicker.min.css">
<link rel="stylesheet" href="~/Areas/Content/plugins/datepicker/datepicker3.css">

        }
@section jsplugin{
    <link rel="stylesheet" href="~/Areas/Content/plugins/timepicker/bootstrap-timepicker.min.js">
<link rel="stylesheet" href="~/Areas/Content/plugins/timepicker/bootstrap-timepicker.js">
<link rel="stylesheet" href="~/Areas/Content/plugins/datepicker/bootstrap-datepicker.js">
<link rel="stylesheet" href="~/Areas/Content/plugins/daterangepicker/daterangepicker.js">
<link rel="stylesheet" href="~/Areas/Content/plugins/datepicker/locales/bootstrap-datepicker.tr.js">



    }
@section scripts{
    <script type="text/javascript">
        $("#datemask").inputmask("dd/mm/yyyy", { "placeholder": "Gün/Ay/Yıl" });

    </script>
    
}

Areas/Admin/Views/Slider/Delete.cshtml
@model g139010027_Proje.Models.Yazilar

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<h2>Sil</h2>
Silmek istediğinize emin misiniz?
<br/>
Basligi 
@Model.YaziBaslik
olan yaziyi silmeyi
<br />
<h3>@Html.ActionLink("Kabul Ediyorum.", "DeleteConfirm", new { id = Model.YaziID })
</h3>
<h3>@Html.ActionLink("Kabul Etmiyorum.", "Index")
</h3>

Areas/Admin/Views/Slider/Edit.cshtml
@model g139010027_Proje.Models.Yazilar

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Haber</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.YaziID)

        <div class="form-group">
            @Html.LabelFor(model => model.YaziBaslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YaziBaslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YaziBaslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YaziIcerik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YaziIcerik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YaziIcerik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YaziTarih, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YaziTarih, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YaziTarih, "", new { @class = "text-danger" })
            </div>
        </div>

     

        <div class="form-group">
            @Html.LabelFor(model => model.YaziResim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YaziResim, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YaziResim, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Slide Tablosuna Dön", "Index")
</div>

Areas/Admin/Views/Slider/Index.cshtml
@model List<g139010027_Proje.Models.Yazilar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Slider Tablosu</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                       
                        <th>Yazi Baslik</th>
                        <th>Yazi Detay</th>
                        <th>Yazi Tarih</th>
                        <th>Yazi Resim Yolu</th>
                      
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.YaziID</td>
                            
                            <td>@item.YaziBaslik </td>
                            <td>@item.YaziIcerik</td>
                            <td>@item.YaziTarih</td>
                            <td>@item.YaziResim</td>
                          
                            <td>@Html.ActionLink("Düzenle","Edit","Slider",new {id=item.YaziID }, null)|@Html.ActionLink("Sil", "Delete", "Slider", new { id = item.YaziID }, null)</td>

                        </tr>
                    }
                </tbody>
                <tfoot>
                   
                </tfoot>
            </table>
        </div><!-- /.box-body -->
    </div><!-- /.box -->
</div>