Areas/Admin/Controllers/ProjeController.cs
using g139010027_Proje.Areas.Admin.Models;
using g139010027_Proje.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace g139010027_Proje.Areas.Admin.Controllers
{
    public class ProjeController : Controller
    {
        OtickDbEntities db = new OtickDbEntities();

        // GET: Admin/Slider
        public ActionResult Index()
        {
           var model= db.Projeler.OrderByDescending(x=>x.ProjeID).ToList();
            return View(model);
        }
        public ActionResult Add() {
            
            return View();

        }
        public ActionResult Delete(int id)
        {
            var model=db.Projeler.Find(id);
            return View(model);

        }
        public ActionResult DeleteConfirm(int id)
        {
            var model = db.Projeler.Find(id);
            db.Projeler.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model=db.Projeler.Find(id);
            return View(model);

        }
        [HttpPost]
        public ActionResult Edit(ProjeModel model)
        {
            if (ModelState.IsValid)
            {



                var bulunan = db.Projeler.Find(model.ProjeID);
                bulunan.ProjeAdi = model.ProjeAdi;
                bulunan.ProjeAciklama = model.ProjeAciklama;
                bulunan.ProjeTarih = model.ProjeTarih;
          

                db.SaveChanges();
            }
            //else
            //{
            //    return View(model);
            //}
            return RedirectToAction("Index");

        }
        const string imageFolderPath = "/Content/img/";
        public ActionResult AddProje(ProjeModel model) {
            if (ModelState.IsValid)
            {
                string fileName = string.Empty;
                //dosya kaydetme
                if (model.ProjeResim!=null&&model.ProjeResim.ContentLength>0)
                {
                     fileName = model.ProjeResim.FileName;
                    var path= Path.Combine(Server.MapPath("~" + imageFolderPath),fileName);

                     model.ProjeResim.SaveAs(path);
                }
                //ef nesnesi
                Projeler hb = new Projeler();
                hb.ProjeAciklama = model.ProjeAciklama;
                hb.ProjeAdi = model.ProjeAdi;
                hb.ProjeTarih = model.ProjeTarih;
             
                hb.ProjeResim =imageFolderPath + fileName;

                db.Projeler.Add(hb);
               db.SaveChanges();
            }
            return RedirectToAction("Index");

        }

    }
}

Areas/Admin/Views/Proje/Add.cshtml
@model g139010027_Proje.Areas.Admin.Models.ProjeModel

@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>
   Proje Ekleme
</h1>
@using (Html.BeginForm("AddProje", "Proje", FormMethod.Post, new { @class = "form-horizontal",enctype="multipart/form-data" }))
{
     
   
        <!-- general form elements disabled -->
        <div class="box box-warning">
            <div class="box-header with-border">
                <h3 class="box-title">Yeni Slider Ekleme</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <form role="form">
                    <div class="form-group">
                        <label class="col-sm-3 control-label">@Html.LabelFor(m => m.ProjeAdi)</label>
                        <div class="col-sm-6">
                            @Html.TextBoxFor(m => m.ProjeAdi, new { @class = "form-control", placeholder = "Proje Adı :" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">@Html.LabelFor(m => m.ProjeAciklama) </label>
                        <div class="col-sm-6">
                            @Html.TextAreaFor(m => m.ProjeAciklama, new { @class = "form-control", placeholder = "Açıklama: " })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">@Html.LabelFor(m => m.ProjeTarih)</label>
                    <div class="col-sm-6">
                         <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                                    </div>
        @Html.TextBoxFor(m => m.ProjeTarih, new { @class = "form-control datepicker", placeholder = "Gün/Ay/Yıl", id = "datemask" })
    </div>

</div><!-- /.input group -->
                    </div><!-- /.form group -->
                        

            
                    <div class="form-group">
                        <label class="col-sm-3 control-label">@Html.LabelFor(m => m.ProjeResim)</label>
                        <div class="col-sm-6">
                            @Html.TextBoxFor(m => m.ProjeResim, new { @class = "form-control", placeholder = "Proje Resmi", type = "file" })
                        </div>
                    </div>


                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-sm-6 col-sm-offset-3">
                                <div class="btn-toolbar">
                                    <button type="submit" class="btn btn-default">İPTAL</button>
                                    <button type="submit" class="btn btn-primary pull-right">EKLE</button>
                                </div>
                            </div>
                        </div>

                    </div>
                </form>    
            </div>  
         
            </div>
       
        }
    @section plugincss{
        <link rel="stylesheet" href="~/Areas/Content/plugins/timepicker/bootstrap-timepicker.css">
<link rel="stylesheet" href="~/Areas/Content/plugins/timepicker/bootstrap-timepicker.min.css">
<link rel="stylesheet" href="~/Areas/Content/plugins/datepicker/datepicker3.css">

        }
@section jsplugin{
    <link rel="stylesheet" href="~/Areas/Content/plugins/timepicker/bootstrap-timepicker.min.js">
<link rel="stylesheet" href="~/Areas/Content/plugins/timepicker/bootstrap-timepicker.js">
<link rel="stylesheet" href="~/Areas/Content/plugins/datepicker/bootstrap-datepicker.js">
<link rel="stylesheet" href="~/Areas/Content/plugins/daterangepicker/daterangepicker.js">
<link rel="stylesheet" href="~/Areas/Content/plugins/datepicker/locales/bootstrap-datepicker.tr.js">



    }
@section scripts{
    <script type="text/javascript">
        $("#datemask").inputmask("dd/mm/yyyy", { "placeholder": "Gün/Ay/Yıl" });

    </script>
    
}

Areas/Admin/Views/Proje/Delete.cshtml
@model g139010027_Proje.Models.Projeler

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<h2>Sil</h2>
Silmek istediğinize emin misiniz?
<br/>
Adi :  
@Model.ProjeAdi
olan projeyi silmeyi
<br />
<h3>@Html.ActionLink("Kabul Ediyorum.", "DeleteConfirm", new { id = Model.ProjeID })
</h3>
<h3>@Html.ActionLink("Kabul Etmiyorum.", "Index")
</h3>

Areas/Admin/Views/Proje/Edit.cshtml
@model g139010027_Proje.Models.Projeler

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Proje:</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProjeID)

        <div class="form-group">
            @Html.LabelFor(model => model.ProjeAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjeAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjeAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProjeAciklama, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjeAciklama, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjeAciklama, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProjeTarih, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjeTarih, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjeTarih, "", new { @class = "text-danger" })
            </div>
        </div>

     

        <div class="form-group">
            @Html.LabelFor(model => model.ProjeResim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjeResim, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjeResim, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Anasayfaya Dön", "Index")
</div>

Areas/Admin/Views/Proje/Index.cshtml
@model List<g139010027_Proje.Models.Projeler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Slider Tablosu</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                       
                        <th>Proje Baslik</th>
                        <th>Proje Detay</th>
                        <th>Proje Tarih</th>
                        <th>Proje Resim Yolu</th>
                      
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.ProjeID</td>
                            
                            <td>@item.ProjeAdi </td>
                            <td>@item.ProjeAciklama</td>
                            <td>@item.ProjeTarih</td>
                            <td>@item.ProjeResim</td>
                          
                            <td>@Html.ActionLink("Düzenle","Edit","Proje",new {id=item.ProjeID }, null)|@Html.ActionLink("Sil", "Delete", "Proje", new { id = item.ProjeID }, null)</td>

                        </tr>
                    }
                </tbody>
                <tfoot>
                   
                </tfoot>
            </table>
        </div><!-- /.box-body -->
    </div><!-- /.box -->
</div>